In [13]:
import numpy as np
import pandas as pd

**Section A: Data Structures & Control Structures**

In [1]:
# Function to create and return an initial list of 5 integers
def create_list():
    # Initial list of 5 integers
    return [10, 20, 30, 40, 50]

# Helper function to print the current state of the list with a label
def print_list(label, lst):
    print(f"{label}: {lst}")

def main():
    # Step 1: Create the initial list
    numbers = create_list()
    print_list("Initial list", numbers)

    # 1. append(): Add a single element at the end of the list
    numbers.append(60)  # Appends 60 to the list
    print_list("After append(60)", numbers)

    # 2. extend(): Add multiple elements from another iterable at the end
    numbers.extend([70, 80])  # Extends the list with 70 and 80
    print_list("After extend([70, 80])", numbers)

    # 3. insert(): Insert an element at a specific index
    numbers.insert(2, 25)  # Inserts 25 at index 2
    print_list("After insert(2, 25)", numbers)

    # 4. remove(): Remove the first occurrence of a value
    numbers.remove(40)  # Removes the first occurrence of 40
    print_list("After remove(40)", numbers)

    # 5. pop(): Remove and return element at given index (default last)
    popped_value = numbers.pop()  # Pops the last element
    print_list(f"After pop() -> popped {popped_value}", numbers)

    # 6. index(): Get the index of the first occurrence of a value
    index_30 = numbers.index(30)  # Finds index of value 30
    print(f"Index of 30: {index_30}")

    # 7. count(): Count occurrences of a value
    count_20 = numbers.count(20)  # Counts how many times 20 appears
    print(f"Count of 20: {count_20}")

    # 8. sort(): Sort the list in ascending order
    numbers.sort()
    print_list("After sort()", numbers)

    # 9. reverse(): Reverse the elements of the list in place
    numbers.reverse()
    print_list("After reverse()", numbers)

    # 10. clear(): Remove all elements from the list
    numbers.clear()
    print_list("After clear()", numbers)

# Execute main function
if __name__ == "__main__":
    main()

Initial list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop() -> popped 80: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]
After clear(): []


In [3]:
# Create a tuple with 3 student names
students = ("Alice", "Bob", "Charlie")

# Try to change the second name
students[1] = "David"   # This will raise an error

TypeError: 'tuple' object does not support item assignment

In [5]:
# Create a set of integers with duplicates
numbers = {1, 2, 2, 3, 4, 4, 4, 5}

print(numbers)

{1, 2, 3, 4, 5}


In [7]:
# Create a dictionary with the given keys
person = {
    "name": "Alice",
    "age": 20,
    "city": "Bengaluru"
}

# Update the age
person["age"] = 21

# Add a new key 'email'
person["email"] = "alice@example.com"

# Print the final dictionary
print(person)

{'name': 'Alice', 'age': 21, 'city': 'Bengaluru', 'email': 'alice@example.com'}


In [8]:
# Variable storing the person's age
age = 17  # You can change this value to test

# Check voting eligibility
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

You are not eligible to vote.


In [9]:
# Given marks
marks = 83  # change this value to test

if marks >= 90:
    print("Grade: A")
elif 75 <= marks <= 89:
    print("Grade: B")
elif 50 <= marks <= 74:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [10]:
# Given number
number = 4  # Change this to test different values

if number > 0:
    if number % 2 == 0:
        print(f"{number} is positive and even")
    else:
        print(f"{number} is positive but odd")
elif number == 0:
    print("The number is zero")
else:
    print(f"{number} is negative")

4 is positive and even


**Section B: Numpy**

In [14]:
# Scalar (0-D array)
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array with values 1 to 5
array_1d = np.arange(1, 6)
print("1D array:", array_1d)

# 2D array (2x3) with values 10 to 60 in steps of 10
array_2d = np.arange(10, 61, 10).reshape(2, 3)
print("2D array:\n", array_2d)

Scalar: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [15]:
# Generate a 4x4 NumPy array of random integers between 0 and 100
random_array = np.random.randint(0, 100, size=(4, 4))

print("4x4 random integer array:\n", random_array)

4x4 random integer array:
 [[94 59  9 80]
 [63 65  2 58]
 [64  9 58 50]
 [19 49 65 41]]


In [16]:
# Create a 3x3 2D NumPy array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Convert to pandas DataFrame with column names 'A', 'B', 'C'
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


**Section C: Exploring Pandas**

In [19]:
# Create a small DataFrame with 10 rows (including some NaN and duplicates)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve',
             'Frank', 'Alice', 'Bob', 'Grace', 'Henry'],
    'Age': [25, 30, 35, 28, 32, 40, 25, 30, 27, 33],
    'City': ['NYC', 'LA', 'Chicago', 'NYC', 'Boston',
             'LA', 'NYC', 'LA', 'Miami', 'Chicago'],
    'Salary': [50000, 60000, np.nan, 55000, 65000,
               70000, 50000, 60000, np.nan, 62000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
print("\n" + "="*50)

# 1. Use .info() and .describe()
print("\n.info():")
print(df.info())
print("\n.describe():")
print(df.describe())

# 2. Select 'Name' and 'City' columns
name_city = df[['Name', 'City']]
print("\nName and City columns:")
print(name_city)

# 3. Drop 'City' column (create new DataFrame)
df_no_city = df.drop('City', axis=1)
print("\nAfter dropping City:")
print(df_no_city)

# 4. Fill missing values in 'Salary' with mean
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nAfter filling NaN in Salary with mean:")
print(df)

# 5. Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nAfter removing duplicates:")
print(df_no_duplicates)


Original DataFrame:
      Name  Age     City   Salary
0    Alice   25      NYC  50000.0
1      Bob   30       LA  60000.0
2  Charlie   35  Chicago      NaN
3    David   28      NYC  55000.0
4      Eve   32   Boston  65000.0
5    Frank   40       LA  70000.0
6    Alice   25      NYC  50000.0
7      Bob   30       LA  60000.0
8    Grace   27    Miami      NaN
9    Henry   33  Chicago  62000.0


.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

.describe():
             Age      Salary
count  10.000000      8.0000
mean   30.500000  59000.0000
std     4.696334   7030.5456
min    25.000000  50000.0000
25%    27.250000  53750.0000
50%    30.00

/tmp/ipython-input-3994682699.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
